export const people = [
  {
    id: 1,
    PersonName: "John Smith",
    Avatar: "profile1.svg",
    PubDate: "2023-09-15",
    Rating: 4.5,
    Commentary: "Great service, very helpful staff.",
    Topic: "Adventure",
    password: "1111",
    email: "profile1@gmail.com",
    city: "Astana",
  },
  {
    id: 2,
    PersonName: "Jane Doe",
    Avatar: "profile2.svg",
    PubDate: "2023-08-22",
    Rating: 3.8,
    Commentary: "Decent product, but shipping took too long.",
    Topic: "Adventure",
    password: "1111",
    email: "profile2@gmail.com",
    city: "Astana",
  },
  {
    id: 26,
    PersonName: "LOL LOL",
    Avatar: "profile2.svg",
    PubDate: "2023-08-22",
    Rating: 1.8,
    Commentary: "Decent product, but shipping took too long.",
    Topic: "Adventure",
    password: "1111",
    email: "profile3@gmail.com",
    city: "Astana",
  },
  {
    id: 3,
    PersonName: "Alice Johnson",
    Avatar: "profile3.svg",
    PubDate: "2023-09-10",
    Rating: 4.9,
    Commentary: "Absolutely loved the experience, would recommend.",
    Topic: "Adventure",
    password: "1111",
    email: "profile4@gmail.com",
    city: "Astana",
  },
  {
    id: 4,
    PersonName: "Bob Lee",
    Avatar: "profile4.svg",
    PubDate: "2023-09-01",
    Rating: 2.5,
    Commentary: "Poor quality, not as expected.",
    Topic: "Adventure",
    password: "1111",
    email: "profile5@gmail.com",
    city: "Astana",
  },
  {
    id: 5,
    PersonName: "Charlie Brown",
    Avatar: "profile1.svg",
    PubDate: "2023-08-29",
    Rating: 4.7,
    Commentary: "Great value for money, very satisfied.",
    Topic: "Nature",
    password: "1111",
    email: "profile6@gmail.com",
    city: "Astana",
  },
  {
    id: 6,
    PersonName: "David Miller",
    Avatar: "profile2.svg",
    PubDate: "2023-08-14",
    Rating: 3.6,
    Commentary: "It was okay, nothing special.",
    Topic: "Nature",
    password: "1111",
    email: "profile7@gmail.com",
    city: "Astana",
  },
  {
    id: 7,
    PersonName: "Emily Davis",
    Avatar: "profile3.svg",
    PubDate: "2023-09-18",
    Rating: 5.0,
    Commentary: "Amazing! Will definitely come back.",
    Topic: "Nature",
    password: "1111",
    email: "profile8@gmail.com",
    city: "Astana",
  },
  {
    id: 8,
    PersonName: "Frank Wilson",
    Avatar: "profile4.svg",
    PubDate: "2023-09-02",
    Rating: 4.0,
    Commentary: "Good overall, but room for improvement.",
    Topic: "Nature",
    password: "1111",
    email: "profile9@gmail.com",
    city: "Astana",
  },
  {
    id: 9,
    PersonName: "Grace Hill",
    Avatar: "profile1.svg",
    PubDate: "2023-09-11",
    Rating: 4.2,
    Commentary: "Nice experience, friendly staff.",
    Topic: "Fashion",
    password: "1111",
    email: "profile10@gmail.com",
    city: "Astana",
  },
  {
    id: 10,
    PersonName: "Henry Scott",
    Avatar: "profile2.svg",
    PubDate: "2023-08-30",
    Rating: 2.8,
    Commentary: "Not satisfied with the quality.",
    Topic: "Fashion",
    password: "1111",
    email: "profile11@gmail.com",
    city: "Astana",
  },
  {
    id: 11,
    PersonName: "Isabella King",
    Avatar: "profile3.svg",
    PubDate: "2023-09-03",
    Rating: 4.9,
    Commentary: "Fantastic service, will recommend to friends.",
    Topic: "Fashion",
    password: "1111",
    email: "profile12@gmail.com",
    city: "Astana",
  },
  {
    id: 12,
    PersonName: "Jack White",
    Avatar: "profile4.svg",
    PubDate: "2023-09-12",
    Rating: 3.5,
    Commentary: "Average, nothing special.",
    Topic: "Fashion",
    password: "1111",
    email: "profile13@gmail.com",
    city: "Astana",
  },
  {
    id: 13,
    PersonName: "Karen Green",
    Avatar: "profile1.svg",
    PubDate: "2023-09-05",
    Rating: 4.6,
    Commentary: "Very happy with the product and service.",
    Topic: "Modern",
    password: "1111",
    email: "profile14@gmail.com",
    city: "Astana",
  },
  {
    id: 14,
    PersonName: "Liam Martinez",
    Avatar: "profile2.svg",
    PubDate: "2023-09-16",
    Rating: 4.1,
    Commentary: "Good, but can improve in certain areas.",
    Topic: "Modern",
    password: "1111",
    email: "profile15@gmail.com",
    city: "Astana",
  },
  {
    id: 15,
    PersonName: "Mia Harris",
    Avatar: "profile3.svg",
    PubDate: "2023-08-27",
    Rating: 3.9,
    Commentary: "Service was nice but the product lacked quality.",
    Topic: "Modern",
    password: "1111",
    email: "profile16@gmail.com",
    city: "Astana",
  },
  {
    id: 16,
    PersonName: "Noah Thompson",
    Avatar: "profile4.svg",
    PubDate: "2023-09-08",
    Rating: 5.0,
    Commentary: "Excellent experience, very professional.",
    Topic: "Modern",
    password: "1111",
    email: "profile17@gmail.com",
    city: "Astana",
  },
  {
    id: 17,
    PersonName: "Olivia Clark",
    Avatar: "profile1.svg",
    PubDate: "2023-09-13",
    Rating: 4.4,
    Commentary: "Good service, but could be more responsive.",
    Topic: "Books",
    password: "1111",
    email: "profile18@gmail.com",
    city: "Astana",
  },
  {
    id: 18,
    PersonName: "Paul Baker",
    Avatar: "profile2.svg",
    PubDate: "2023-09-07",
    Rating: 2.9,
    Commentary: "Not very impressed with the overall experience.",
    Topic: "Books",
    password: "1111",
    email: "profile19@gmail.com",
    city: "Astana",
  },
  {
    id: 19,
    PersonName: "Quincy Perez",
    Avatar: "profile3.svg",
    PubDate: "2023-09-19",
    Rating: 4.3,
    Commentary: "Overall good, a few areas need work.",
    Topic: "Books",
    password: "1111",
    email: "profile20@gmail.com",
    city: "Astana",
  },
  {
    id: 20,
    PersonName: "Rachel Young",
    Avatar: "profile4.svg",
    PubDate: "2023-09-20",
    Rating: 4.8,
    Commentary: "Really great product and excellent service.",
    Topic: "Books",
    password: "1111",
    email: "profile21@gmail.com",
    city: "Astana",
  },
];
